version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2008
      POSTGRES_DB: docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-service
    ports:
      - "6300:6379"
    restart: always

  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "

volumes:
  postgres_data:
